[build.environment]
  NODE_VERSION = "18.18.0"

[build]
  command = "yarn build"
  publish = "dist"

[[redirects]]
  from = "/vip"
  to = "/topgrillin"
  status = 301
  force = true

[[redirects]]
  from = "/bastidsbbq"
  to = "https://www.skratchbastid.live/bastidsbbq"
  status = 301
  force = true

[[redirects]]
  from = "/bastidsbbq/"
  to = "https://www.skratchbastid.live/bastidsbbq"
  status = 301
  force = true
