name: Mirror to Personal Repository

on:
  push:
    branches:
      - main  # or your default branch name

permissions:
  contents: write  # Granting read and write access

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Push to personal repository
        env:
          PERSONAL_REPO_TOKEN: ${{ secrets.PERSONAL_REPO_TOKEN }}
        run: |
          git remote add personal https://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@github.com/skratchbastid/skratchbastid.com.git
          git push personal --mirror
