name: Mirror to Personal Repository

on:
  push:
    branches:
      - main  # or your default branch name

permissions:
  contents: write  # Granting read and write access

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Debug Info Before
        run: |
          echo "Current directory: $(pwd)"
          echo "Repository contents:"
          ls -la
          echo "Git configuration:"
          git config --list
          echo "Git remotes:"
          git remote -v
          echo "Git branches:"
          git branch -a
          echo "Git status:"
          git status

      - name: Push to personal repository
        env:
          PERSONAL_REPO_TOKEN: ${{ secrets.PERSONAL_REPO_TOKEN }}
        run: |
          echo "Adding personal remote..."
          git remote add personal https://oauth2:${PERSONAL_REPO_TOKEN}@github.com/skratchbastid/test.git
          echo "Git remotes after adding personal:"
          git remote -v
          echo "Pushing to personal remote..."
          git push personal --mirror --verbose
        continue-on-error: true

      - name: Check for errors
        if: failure()
        run: |
          echo "Push failed. Here's some debug info:"
          echo "Current directory: $(pwd)"
          echo "Repository contents:"
          ls -la
          echo "Git configuration:"
          git config --list
          echo "Git remotes:"
          git remote -v
          echo "Git status:"
          git status
          echo "Last commit:"
          git log -1
          echo "Git error log:"
          git config --get-all http.https://github.com/.extraheader || echo "No error log found"

      - name: Check token (safe version)
        run: |
          TOKEN_PREFIX="${PERSONAL_REPO_TOKEN:0:4}"
          TOKEN_SUFFIX="${PERSONAL_REPO_TOKEN: -4}"
          echo "Token starts with $TOKEN_PREFIX and ends with $TOKEN_SUFFIX"
          echo "Token length: ${#PERSONAL_REPO_TOKEN}"
        env:
          PERSONAL_REPO_TOKEN: ${{ secrets.PERSONAL_REPO_TOKEN }}
