name: Mirror to Personal Repo

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Debug Info
        run: |
          echo "GitHub Actor: ${{ github.actor }}"
          echo "GitHub Ref: ${{ github.ref }}"
          echo "Repo visibility: ${{ github.event.repository.visibility }}"

      - name: Push to Personal Repo
        env:
          PERSONAL_REPO_URL: ${{ secrets.PERSONAL_REPO_URL }}
          PERSONAL_REPO_TOKEN: ${{ secrets.PERSONAL_REPO_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          echo "Adding remote..."
          git remote add personal-repo https://${PERSONAL_REPO_TOKEN}@github.com/skratchbastid/skratchbastid.com.git
          echo "Listing remotes..."
          git remote -v
          echo "Pushing to remote..."
          git push personal-repo main:main --force
        continue-on-error: true

      - name: Check Push Result
        if: always()
        run: |
          echo "Checking remote..."
          git remote -v
          echo "Attempting to fetch from personal-repo..."
          git fetch personal-repo || echo "Fetch failed"
          echo "Listing branches..."
          git branch -a
          echo "Checking token permissions..."
          curl -H "Authorization: token ${{ secrets.PERSONAL_REPO_TOKEN }}" https://api.github.com/user