name: Mirror to Personal Repository

on:
  push:
    branches:
      - main  # or your default branch name

permissions:
  contents: read  # Updated to follow best practices

jobs:
  mirror:
    name: Mirror Repository
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Push to personal repository
        env:
          PERSONAL_REPO_TOKEN: ${{ secrets.PERSONAL_REPO_TOKEN }}
        run: |
          git remote add personal "https://${PERSONAL_REPO_TOKEN}@github.com/skratchbastid/test.git"
          git push personal --mirror
        
      - name: Check for errors
        if: failure()
        run: |
          echo "Push failed. Debug info:"
          git remote -v
          git status
          git log -1
