name: Mirror to Personal Repo  # Name of the workflow

on:
  push:
    branches:
      - main  # The workflow will trigger on a push to the 'main' branch

jobs:  # Define the jobs this workflow will run
  mirror:  # Name of the job
    runs-on: ubuntu-latest  # Specify the environment (runner) the job will run on (Ubuntu in this case)

    steps:  # Define each step that the job will perform
      - name: Checkout Repository  # Step 1
        uses: actions/checkout@v3  # GitHub's official action to checkout your repo code

      - name: Push to Personal Repo  # Step 2
        run: |
          git remote add personal-repo https://$PERSONAL_REPO_TOKEN@github.com/skratchbastid/skratchbastid.com.git
          git push personal-repo main --force
        env:
          PERSONAL_REPO_TOKEN: ${{ secrets.PERSONAL_REPO_TOKEN }}  # GitHub secret storing the Personal Access Token (PAT)

permissions:
  contents: write  # Ensure the workflow has write access to the repository contents